---
# tasks file for react
  - name: create build directory
    file:
      path: "{{ container_path }}"
      state: directory
      owner: root
      group: root
      mode: '0755'
# at this point do not forget change DB_HOST env variable for postgresql node
  - name: copy files to the react node
    copy:
      src: /home/ec2-user/ansible-project/todo-app-pern/client/
      dest: "{{ container_path }}"
  - name: copy the Dockerfile
    copy:
      src: /home/ec2-user/ansible-project/react/Dockerfile
      dest: "{{ container_path }}"
  - name: remove {{ container_name }} container and {{ image_name }} image if exists
    shell: "docker ps -q --filter 'name={{ container_name }}' && docker stop {{ container_name }} && docker rm -fv {{ container_name }} && docker image rm -f {{ image_name }} || echo 'Not Found'"
  - name: build container image
    docker_image:
      name: "{{ image_name }}"
      build:
        path: "{{ container_path }}"
      source: build
      state: present
  - name: Launch react docker container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: started
      ports:
      - "3000:3000"
